
waitUntil {!(isNull player)};
waitUntil {player==player};
switch (side player) do
{
case WEST:
{
player createDiaryRecord ["Diary",["Persistência","Contra a Insurgência o combate é desafiador e requer uma abordagem diferente das operações regulares. <br/><br/>A inteligência é vital para enfraquecer a Insurgência e entender como ela funciona. Os insurgentes irão evitar um confronto direto com as Forças de Segurança. Irão realizar sabotagens e ataques enquanto tentam recrutar novos combatentes. <br/><br/>Eles irão ocupar instalações, fábricas, depósitos de armas e zonas de recrutamento. Eles preferem atacar instalações militares e civis desprotegidas que estão perto do QG da Insurgência, caso sejam bem-sucedidos, a hostilidade será elevada e eles irão começar a realizar emboscadas e ataques a instalações ocupadas.<br/><br/> Acompanhar os movimentos dos insurgentes e a identificação de prováveis alvos, vai ajudar as Forças de Segurança a direcionar seus recursos limitados de forma eficaz. <br/>NOTA"]];
player createDiaryRecord ["Diary",["Os insurgentes Civis","Todos os dados da missão são armazenados em um banco de dados. Isso inclui a última posição de seu combatente, inventario, danos físicos, SitRep, etc. Não existe respawn de veículos. Levam muitos dias para os suprimentos chegarem a sua base. Está previsto um Backup diário do Banco de dados, esse processo demora média de 60 minutos."]];
player createDiaryRecord ["Diary",["Células Insurgentes","Com as Células Insurgente recrutando e coagindo os civis, a situação de segurança vai deteriorar-se e civis pacíficos serão transformados em insurgentes civis hostis. Se houver uma fábrica IED, deposito de armas ou zona de recrutamento na área, ocasionalmente civis serão coagidos a pegar armas ou explosivos, e serão enviados em missões de apoio à insurgência. As Força de Segurança podem detectar esses insurgentes civis, monitorando seu comportamento ou abordando e revistando. <br/><br/><img image='images\guerra3.jpg' width='350' height='173'/> <br/><img image='images\guerra4.jpg' width='350' height='173'/><br/><br/>Sabotagem - Insurgentes irão recolher explosivos a partir de um Deposito de Armas e partir para destruir alvos e infraestrutura, como fábricas e usinas de energia, a fim de desestabilizar a situação de segurança. Eles tentarão colocar de 3 a 5 cargas explosivas perto do prédio para detonação a distância segura. Se forem bemsucedidos, isso terá um grande impacto sobre o nível de hostilidade e a moral dos insurgentes.<br/><br/>• Civis Coagidos - Civis coagidos irão pegar armas escondidas em depósitos e em seguida, misturar-se com a população civil local até que uma patrulha das forças de segurança apareça. <br/><br/>• Homens-Bomba - Irão utilizar locais com bastante civis ou forças de segurança para efetuar a detonação.   <br/><br/><br/>"]];
player createDiaryRecord ["Diary",["Guerra Assimétrica","Células insurgentes serão inicialmente criadas como grupos paramilitares irregulares.  Cidades grandes que estão desprotegidas tendem a se tornar centros de recrutamento para a insurgência crescente. A população civil insatisfeita tem maior tendência em incorporar na causa dos insurgentes. <br/><br/><img image='images\guerra2.jpg' width='350' height='138'/><br/><br/>Uma vez estabelecida, a Guerra Assimétrica, as células insurgentes realizarão uma série de atividades em apoio à insurgência, dependendo da situação e da ameaça atual na área. <br/><br/>• Obstáculos - Estabelecer barreiras em zonas controladas permitirá que os insurgentes dominem a população civil local e estabeleçam defesas rudimentares contra as Forças de Oposição.<br/><br/>• Deposito de Armas - insurgentes tentarão armazenar munições e armas em locais escondidos durante toda AO, que serão utilizados para equipar combatentes recrutados.    <br/> 7 www.zonadecombate.com.br   <br/>Ver. 1.0 <br/>  <br/>NPA-001 OPERAÇÕES   <br/><br/>• Fábricas IED - Fabricas para preparar IED serão estabelecidas em locais escondidos em toda a AO. IEDs são o método preferido dos insurgentes para ataque contra as Forças de Oposição. <br/><br/>• Emboscadas - Insurgentes tentarão emboscar patrulhas militares e comboios a céu aberto, utilizando uma combinação de IED ou usando a técnica Atacar e Correr.<br/><br/>• Assaltos - Ataques a postos militares e bases de patrulha, são uma forma de ataque insurgente.  <br/><br/>• Zona de Recrutamento - Os insurgentes vão estabelecer uma Zona de Recrutamento perto de locais civis, eles vão recrutar e armar novos combatentes entre a população civil. <br/><br/>• Coerção - células insurgentes irão coagir civis e o tornarão homens-bomba, atiradores e sabotadores. <br/><br/>"]];
player createDiaryRecord ["Diary",["Nossa Missão","Guerra Assimétrica é um estilo de combate que difere de ocupação e invasão, em aspectos importantes. Comandantes insurgentes têm diferentes objetivos, táticas e armas. Seu objetivo é acabar com seu inimigo, desestabilizar a situação de segurança e gerar confusão envolvendo as Forças de Segurança. Eles empregam táticas, como sabotagem, ataque do tipo “Bater e Correr”, bloqueios de estradas, IEDs e homens-bomba. Eles tentam se misturar com a população civil, a fim de mover armas e explosivos para locais estratégicos. <br/>A pesquisa e monitoramento da atividade civil completa pode ajudar a reduzir a ameaça. <br/><br/><img image='images\guerra1.jpg' width='350' height='138'/><br/><br/>Buscar informações e inteligência é a chave para desmontar as operações dos insurgentes em todo o território.  Existe uma área concentrada de insurgentes onde é o centro da zona de revolta. E a partir dessa área eles irão se mover para instalações desguarnecidas e vilas para recrutar a população.<br/><br/>"]];
};
case EAST:
{
};
case RESISTANCE:
{
};
case CIVILIAN:
{
};
};
