/*
 * TRANSLATION FILE (ENGLIGH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Levante a carga";
STR_R3F_LOG_action_heliporter_fait = "Carga ""%1"" içada.";
STR_R3F_LOG_action_heliport_larguer = "Largar a carga";
STR_R3F_LOG_action_heliport_larguer_fait = "Carga ""%1"" largada.";
STR_R3F_LOG_action_heliport_attente = "prendendo a carga... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Enganche abortado ! Fique em foco durante o enganche.";

STR_R3F_LOG_action_deplacer_objet = "Pegar ""%1""";
STR_R3F_LOG_action_relacher_objet = "Largar ""%1""";
STR_R3F_LOG_action_aligner_pente = "Ajustar à inclinação";
STR_R3F_LOG_action_aligner_sol = "Ajustar para o chão";
STR_R3F_LOG_action_aligner_horizon = "Ajuste horizontalmente";
STR_R3F_LOG_action_tourner = "Vire à esquerda / direita com as teclas (X / C)";
STR_R3F_LOG_action_rapprocher = "Perto/Longe com as teclas (F / R )";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Você não pode entrar em um veículo enquanto você está carregando esse objeto !";

STR_R3F_LOG_action_charger_deplace = "Carga no veículo";
STR_R3F_LOG_action_selectionner_objet_charge = "Carga ""%1"" dentro...";
STR_R3F_LOG_action_charger_selection = "... carga dentro ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Agora, selecione o destino para ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Carregamento em curso...";
STR_R3F_LOG_action_charger_fait = "A carga""%1"" foi carregado em ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Não há espaço suficiente para este objeto neste veículo !";

STR_R3F_LOG_action_remorquer_direct = "Rebocar ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Rebocar o objeto";
STR_R3F_LOG_action_detacher = "Liberar objeto do reboque";
STR_R3F_LOG_action_detacher_fait = "Objeto liberado.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Apenas o piloto pode destacar esse objeto.";

STR_R3F_LOG_action_contenu_vehicule = "Ver o conteúdo do veículo";
STR_R3F_LOG_action_decharger_en_cours = "Descarga em andamento...";
STR_R3F_LOG_action_decharger_fait = "O objeto ""%1"" descarregado a partir do veículo.";
STR_R3F_LOG_action_decharger_deja_fait = "O objeto já foi descarregado !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Uma vez liberado, esse objeto não será mais móvel manualmente<br/>Você confirmar a ação ?";

STR_R3F_LOG_action_ouvrir_usine = "Abra a fábrica de criação";
STR_R3F_LOG_action_creer_en_cours = "Criação em andamento...";
STR_R3F_LOG_action_creer_fait = "O objeto ""%1"" foi criado.";
STR_R3F_LOG_action_creer_pas_assez_credits = "A fábrica tem não créditos suficientes para criar este objeto.";
STR_R3F_LOG_action_revendre_usine_direct = "Devolver ""%1"" para a fábrica";
STR_R3F_LOG_action_revendre_usine_deplace = "Enviar de volta para a fábrica";
STR_R3F_LOG_action_revendre_usine_selection = "... enviar de volta para a fábrica";
STR_R3F_LOG_action_revendre_en_cours = "Enviando de volta para a fábrica...";
STR_R3F_LOG_action_revendre_fait = "O objeto ""%1"" foi enviado de volta para a fábrica.";
STR_R3F_LOG_action_revendre_decharger_avant = "Você não pode enviar de volta, enquanto seu conteúdo carga não está vazio !";

STR_R3F_LOG_mutex_action_en_cours = "A operação atual não está terminada !";
STR_R3F_LOG_joueur_dans_objet = "Há um jogador no objeto ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "O objeto ""%1"" já está em trânsito !";
STR_R3F_LOG_objet_remorque_en_cours = "Impossivel porque o objeto ""%1"" esta rebocando outro objeto !";
STR_R3F_LOG_trop_loin = "Impossivel porque o objeto esta ""%1"" longe demais  !";

STR_R3F_LOG_dlg_CV_titre = "Conteudo do veículo";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Carregando : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "DESCARREGAR";
STR_R3F_LOG_dlg_CV_btn_fermer = "CANCELAR";

STR_R3F_LOG_dlg_LO_titre = "Fábrica de Criação";
STR_R3F_LOG_dlg_LO_credits_restants = "Creditos restantes : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "CRIAR";
STR_R3F_LOG_dlg_LO_btn_fermer = "CANCELAR";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Propriedades";
STR_R3F_LOG_nom_fonctionnalite_side = "Lado";
STR_R3F_LOG_nom_fonctionnalite_places = "Lugares sentados";
STR_R3F_LOG_nom_fonctionnalite_passif = "Pode ser :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "movido pelo jogador";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Içado";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Rebocado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transportado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "Custo de carga %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Isso pode:";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Içar";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Reboque";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transporte";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "Carga máxima %1";

STR_R3F_LOG_deverrouillage_en_cours = "Desbloqueando... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Desbloqueio cancelado!  Mantenha-se próximo ao objeto durante a contagem regressiva.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objeto desbloqueado.";
STR_R3F_LOG_action_deverrouiller = "Unlock ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Objeto bloqueado.";